### ISSUE TITLE
Requesting access as PyCon Taiwan organizer

### ISSUE THREAD

**Issue by tai271828** [python-organizers/conferences#111]
I'm an organizer of ``PyCon Taiwan``. 
Please give me access to this repository.

Thanks!

Ref: The member list of PyCon Taiwan Github repository https://github.com/orgs/pycontw/people

**Comment by invisibleroads** [comment]
Sent invitation. Please close if resolved.

**Comment by tai271828** [comment]
Thanks @invisibleroads . I accepted the invitation and it looks good.
