### ISSUE TITLE
Add column for CFP url

### ISSUE THREAD

**Issue by Mariatta** [python-organizers/conferences#12]
Could be useful info, in addition to the website and sponsorship URLs.

**Comment by hroncok** [comment]
Would the format still be compatible with Google Calendar?

**Comment by Mariatta** [comment]
Reading this [page](https://support.google.com/calendar/answer/37118?hl=en), seems like the relevant columns for Google Calendar are: Subject, Start Date, End Date. The other columns (Sponsor URL, Website URL) are not used by Google Calendar.

So adding a new column wouldn't break Google Calendar, it doesn't have much effect either.

I'm wondering if these extra columns should be moved into the "Description" column?

**Comment by hroncok** [comment]
Well, that would make the data nested, right? I don't think that's too useful.

**Comment by invisibleroads** [comment]
Thanks, @Mariatta and @hroncok. We added a column for "Proposal URL" and tested that everything still imports into Google Calendar.
