### ISSUE TITLE
Add HassanBahati

### ISSUE THREAD

**Issue by HassanBahati** [python-organizers/conferences#198]
I'm an organizer of ``PYCON UGANDA``. @PyconUg 
Please give me access to this repository.

Thanks!

**Comment by HassanBahati** [comment]
@invisibleroads kindly review.

**Comment by invisibleroads** [comment]
Thank you for organizing PyCon Uganda.

Added @HassanBahati

**Comment by HassanBahati** [comment]
> Thank you for organizing PyCon Uganda.
> 
> Added @HassanBahati

It is a pleasure @invisibleroads 🙏 thank you
