### ISSUE TITLE
Overlapping dates for PyCon Asia Pacific and PyCon Korea

### ISSUE THREAD

**Issue by invisibleroads** [python-organizers/conferences#222]
@terapyon @iqbalabd @scari @darjeeling I just noticed that the dates for PyCon Asia Pacific and PyCon Korea overlap.

https://github.com/python-organizers/conferences/issues/89

![gantt](https://github.com/python-organizers/conferences/assets/266668/fc13d260-779a-45da-b764-15bee2c9b16b)

**Comment by scari** [comment]
@invisibleroads Yes, (sadly) it is.
