### ISSUE TITLE
http://www.pycon.org/

### ISSUE THREAD

**Issue by Daniel-at-github** [python-organizers/conferences#40]
Please add a link to http://www.pycon.org/ in the Readme. I think that is the better source for this dataset.

**Comment by hroncok** [comment]
better than what?

**Comment by hroncok** [comment]
It is.

**Comment by invisibleroads** [comment]
Thanks for the suggestion. Fixed in 2b89e091ddadaaa6ff5a1143e8ef01a5c4a60d6e.
