### ISSUE TITLE
Separating Location field

### ISSUE THREAD

**Issue by tylerdave** [python-organizers/conferences#41]
I'm working on a project to automate listing the upcoming Python-related conferences and I'd like to use this repo as a source of data. On thing I'd like to be able to do is filter / separate conferences by region or country. With the current "Location" field it's a little hard to do. Would you be open to separating the field into "City", "Region", "Country" (maybe with "Venue" as well?) or adding those as new fields?

Thanks for maintaining this!

**Comment by tylerdave** [comment]
That makes sense. It looks like additional fields aren't a problem. Would folks be open to me adding City/Region/Country?

**Comment by invisibleroads** [comment]
Hmm, we could add a Country Code column containing the ANSI three letter code of the host country.

Proposed Changes
- Keep Location column. As @jonafato highlighted, the Location column is useful for populating the Location field for each conference event in Google Calendar.
- Add Venue column (name of venue). Recording past venues might be valuable for future conference organizers.
- Add Country Code column (three letter ANSI country code) for easier filtering by country

@tylerdave Would Country Code work for your application?

**Comment by invisibleroads** [comment]
Having an Participant Count column (for recording number of event attendees) might also be interesting.

**Comment by tylerdave** [comment]
Yes, now that I understand the reason for the combined Location column it make sense to leave as-is. 

- Having the country split-out gets me most of what I need and enough for me to work with. I assume you want [ISO 3166-1 alpha 3](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-3) codes? I'd love to also have city and "country subdivision" as well but those aren't show-stoppers for me.
- A separate venue would be nice. 
- Attendee estimate / count would be interesting but not necessary for what I'm trying to do.

I'd be glad to make the changes and PR once I know what you're ok with.

**Comment by invisibleroads** [comment]
You are welcome to add columns as needed.

- Country Code (or Country)
- Venue (or Venue Name)
- Participant Count (or Participants or Attendee Count or Attendees)

If you are looking for administrative regions that are more granular than by country, the [Google Maps Geocoding API](https://developers.google.com/maps/documentation/geocoding/intro#geocoding) might be what you need. Contributors have spelled the same location in different ways and I think the Google Maps Geocoding API will be able to normalize those inconsistencies.

**Comment by tylerdave** [comment]
@pradyunsg Yes. I plan to add columns as discussed. I won't have time to make use of this until mid-August so this'll probably sit until then. I'll submit a PR when I can.
